/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import static OpcionesClientes.DatosFacturacion.datos;
import static OpcionesClientes.RegistrarTarjeta.tarjeta;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Oreld
 */
public class Cotización extends javax.swing.JFrame {
public static ArrayList<Cotiza> cotiza = new ArrayList<Cotiza>();
private double Precio =0;
private int contador =0;
 private String codigoPaquete = "IPC1C5EGM0" ;
    /**
     * Creates new form Cotización
     */
    public Cotización(ArrayList<Cotiza> cotiza) {
        this.cotiza=cotiza;
        initComponents();
        cboTarjetas.removeAllItems();
        int Precio =0;
       
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDepDestino = new javax.swing.JComboBox<>();
        txtMunDestino = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDepOrigen = new javax.swing.JComboBox<>();
        txtMunOrigen = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroPaquete = new javax.swing.JComboBox<>();
        txtCotizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCobro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtDatosFac = new javax.swing.JComboBox<>();
        txtEnviarPago = new javax.swing.JButton();
        txtDatosFacturacion = new javax.swing.JTextField();
        txtFactura = new javax.swing.JToggleButton();
        txtGuia = new javax.swing.JButton();
        txtVolver = new javax.swing.JButton();
        cboTarjetas = new javax.swing.JComboBox<>();
        cboTarjetas1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cotización, pago y descarga de factura y guía");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Origen");

        txtDepDestino.setBackground(new java.awt.Color(255, 255, 255));
        txtDepDestino.setForeground(new java.awt.Color(0, 0, 0));
        txtDepDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metropolitana", "Norte", "Nororiente", "Suroriente", "Suroccidente", "Noroccidente" }));

        txtMunDestino.setBackground(new java.awt.Color(255, 255, 255));
        txtMunDestino.setForeground(new java.awt.Color(0, 0, 0));
        txtMunDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipios" }));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Destino");

        txtDepOrigen.setBackground(new java.awt.Color(255, 255, 255));
        txtDepOrigen.setForeground(new java.awt.Color(0, 0, 0));
        txtDepOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metropolitana", "Norte", "Nororiente", "Suroriente", "Suroccidente", "Noroccidente" }));

        txtMunOrigen.setBackground(new java.awt.Color(255, 255, 255));
        txtMunOrigen.setForeground(new java.awt.Color(0, 0, 0));
        txtMunOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Municipios" }));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tamaño de el paquete");

        txtNumeroPaquete.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroPaquete.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande" }));
        txtNumeroPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroPaqueteActionPerformed(evt);
            }
        });

        txtCotizar.setBackground(new java.awt.Color(102, 102, 255));
        txtCotizar.setForeground(new java.awt.Color(0, 0, 0));
        txtCotizar.setText("Cotizar");
        txtCotizar.setBorder(null);
        txtCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCotizarActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Servicio estandard Q 158.00");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Servicio Especial Q 148.00");

        txtServicio.setBackground(new java.awt.Color(255, 255, 255));
        txtServicio.setForeground(new java.awt.Color(0, 0, 0));
        txtServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicio Estandar", "Servicio Especial" }));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tipo de pago");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cobro contra entrega, Cobro adicional Q 5.00");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cobro a mi cuenta, Pago con tarjeta de crédito o débito");

        txtCobro.setBackground(new java.awt.Color(255, 255, 255));
        txtCobro.setForeground(new java.awt.Color(0, 0, 0));
        txtCobro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cobro contra entrega", "Cobro a mi cuenta" }));
        txtCobro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtCobroItemStateChanged(evt);
            }
        });
        txtCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCobroActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Numero de paquetes");

        txtDatosFac.setBackground(new java.awt.Color(255, 255, 255));
        txtDatosFac.setForeground(new java.awt.Color(0, 0, 0));
        txtDatosFac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Datos de facturación" }));
        txtDatosFac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtDatosFacItemStateChanged(evt);
            }
        });
        txtDatosFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosFacActionPerformed(evt);
            }
        });

        txtEnviarPago.setBackground(new java.awt.Color(102, 102, 255));
        txtEnviarPago.setForeground(new java.awt.Color(0, 0, 0));
        txtEnviarPago.setText("Realizar pago y enviar");
        txtEnviarPago.setBorder(null);
        txtEnviarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnviarPagoActionPerformed(evt);
            }
        });

        txtDatosFacturacion.setBackground(new java.awt.Color(255, 255, 255));
        txtDatosFacturacion.setForeground(new java.awt.Color(0, 0, 0));

        txtFactura.setBackground(new java.awt.Color(102, 102, 255));
        txtFactura.setForeground(new java.awt.Color(0, 0, 0));
        txtFactura.setText("Descargar factura");
        txtFactura.setBorder(null);
        txtFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturaActionPerformed(evt);
            }
        });

        txtGuia.setBackground(new java.awt.Color(102, 102, 255));
        txtGuia.setForeground(new java.awt.Color(0, 0, 0));
        txtGuia.setText("Descargar guia");
        txtGuia.setBorder(null);
        txtGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuiaActionPerformed(evt);
            }
        });

        txtVolver.setBackground(new java.awt.Color(102, 102, 255));
        txtVolver.setForeground(new java.awt.Color(0, 0, 0));
        txtVolver.setText("Volver");
        txtVolver.setBorder(null);
        txtVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolverActionPerformed(evt);
            }
        });

        cboTarjetas.setBackground(new java.awt.Color(102, 102, 255));
        cboTarjetas.setForeground(new java.awt.Color(0, 0, 0));
        cboTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTarjetasActionPerformed(evt);
            }
        });

        cboTarjetas1.setBackground(new java.awt.Color(102, 102, 255));
        cboTarjetas1.setForeground(new java.awt.Color(0, 0, 0));
        cboTarjetas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTarjetas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(392, 392, 392)
                                .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatosFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtEnviarPago)
                                        .addGap(140, 140, 140))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cboTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtDatosFac, 0, 162, Short.MAX_VALUE)
                                                .addComponent(txtCobro, 0, 162, Short.MAX_VALUE)
                                                .addComponent(cboTarjetas1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(114, 114, 114))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(txtCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDepOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMunOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtMunDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDepDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addGap(188, 188, 188))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(124, 124, 124)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepDestino)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMunOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMunDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDatosFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboTarjetas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDatosFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtEnviarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCotizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroPaqueteActionPerformed

    private void txtGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuiaActionPerformed

         File archivo;
        String Factura = "Guia";
        try {
            archivo = new File ("C:\\Users\\Oreld\\Downloads\\"+Factura+".txt");
            if (archivo.createNewFile()) {
                 JOptionPane.showMessageDialog(this,"La guia se a descargado y esta en la tuta correspondiente");
            }else{
                 JOptionPane.showMessageDialog(this,"La guia ya se encuentra en su sistema");
            }
            FileWriter escribir = new FileWriter(archivo, true);
            escribir.write(codigoPaquete);
            escribir.write("  ");
            escribir.write(txtDepOrigen.getSelectedItem().toString());
            escribir.write("  ");
            escribir.write(txtDepDestino.getSelectedItem().toString());
            escribir.write("  ");
            escribir.write(txtCobro.getSelectedItem().toString());
            escribir.write("  ");
            escribir.write(txtNumeroPaquete.getSelectedItem().toString());
            escribir.write("  ");
            escribir.write(String.valueOf(Precio));
            escribir.write("  ");
            escribir.close();
        } catch(Exception e){
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuiaActionPerformed

    private void txtVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolverActionPerformed

        OpcionesClientes pantalla =new  OpcionesClientes(cotiza);
        pantalla.setVisible(true);
        pantalla.setLocationRelativeTo(null);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolverActionPerformed

    private void txtEnviarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnviarPagoActionPerformed

        Cotiza factu0 = new Cotiza(txtDepOrigen.getSelectedItem().toString(), codigoPaquete+contador, txtDepDestino.getSelectedItem().toString(),  String.valueOf(Precio), txtNumeroPaquete.getSelectedItem().toString(), txtDatosFacturacion.getText(), txtServicio.getSelectedItem().toString(), txtCobro.getSelectedItem().toString(), txtDatosFac.getSelectedItem().toString());
        cotiza.add(factu0);
        contador=contador+1;
         JOptionPane.showMessageDialog(this,"Compra realizada con exito, su codigo de paquete es"+codigoPaquete+contador);
    }//GEN-LAST:event_txtEnviarPagoActionPerformed

    private void txtCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCotizarActionPerformed

       String Destino= txtDepDestino.getSelectedItem().toString();
       String Tamaño =txtNumeroPaquete.getSelectedItem().toString();
       int Paquetes= Integer. parseInt(txtDatosFacturacion.getText());
       String Servicio = txtServicio.getSelectedItem().toString();
        if (Destino.equals("Metropolitana")) {
            if (Servicio.equals("Servicio Estandar")) {
                if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*35);
                    Precio=Paquetes*25*35;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*35);
                    Precio=Paquetes*50*35;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*35);
                    Precio=Paquetes*100*35;
                }
                
            }
            if (Servicio.equals("Servicio Especial")) {
                if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*25);
                    Precio=Paquetes*25*25;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*25);
                    Precio=Paquetes*50*25;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*25);
                    Precio=Paquetes*100*25;
                }
        }}
        if (Destino.equals("Norte")) {
            if (Servicio.equals("Servicio Estandar")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*68.50);
                    Precio=Paquetes*25*68.50;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*68.50);
                    Precio=Paquetes*50*68.50;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*68.50);
                    Precio=Paquetes*100*68.50;
                }
            }
            if (Servicio.equals("Servicio Especial")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*45.55);
                    Precio=Paquetes*25*45.55;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*45.55);
                    Precio=Paquetes*50*45.55;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*45.55);
                    Precio=Paquetes*100*45.55;
                }
            }
        }
        if (Destino.equals("Nororiente")) {
            if (Servicio.equals("Servicio Estandar")) { 
                if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*58.68);
                    Precio=Paquetes*25*58.68;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*58.68);
                    Precio=Paquetes*50*58.68;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*58.68);
                    Precio=Paquetes*100*58.68;
                }
            }
            if (Servicio.equals("Servicio Especial")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*35.48);
                    Precio=Paquetes*25*35.48;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*35.48);
                    Precio=Paquetes*50*35.48;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*35.48);
                    Precio=Paquetes*100*35.48;
                }
            }
        }
         if (Destino.equals("Suroriente")) {
            if (Servicio.equals("Servicio Estandar")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*36.68);
                    Precio=Paquetes*25*36.68;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*36.68);
                    Precio=Paquetes*50*36.68;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*36.68);
                    Precio=Paquetes*100*36.68;
                }
            }
            if (Servicio.equals("Servicio Especial")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*32.48);
                    Precio=Paquetes*25*32.48;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*32.48);
                    Precio=Paquetes*50*32.48;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*32.48);
                    Precio=Paquetes*100*32.48;
                }
            }
        }
          if (Destino.equals("Suroccidente")) {
            if (Servicio.equals("Servicio Estandar")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*34);
                    Precio=Paquetes*25*34;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*34);
                    Precio=Paquetes*50*34;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*34);
                    Precio=Paquetes*100*34;
                }
            }
            if (Servicio.equals("Servicio Especial")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*29);
                    Precio=Paquetes*25*29;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*29);
                    Precio=Paquetes*50*29;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*29);
                    Precio=Paquetes*100*29;
                }
            }
        }
           if (Destino.equals("Noroccidente")) {
            if (Servicio.equals("Servicio Estandar")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*44.50);
                    Precio=Paquetes*25*44.50;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*44.50);
                    Precio=Paquetes*50*44.50;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*44.50);
                    Precio=Paquetes*100*44.50;
                }
            }
            if (Servicio.equals("Servicio Especial")) {
                 if (Tamaño.equals("Pequeño")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*25*40);
                    Precio=Paquetes*25*40;
                }
                 if (Tamaño.equals("Mediano")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: " +Paquetes*50*40);
                    Precio=Paquetes*50*40;
                }
                  if (Tamaño.equals("Grande")) {
                    JOptionPane.showMessageDialog(this,"El total de es servicio es: "+Paquetes*100*40);
                    Precio=Paquetes*100*40;
                }
            }
        }
       

    }//GEN-LAST:event_txtCotizarActionPerformed

    private void txtCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCobroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCobroActionPerformed

    private void txtCobroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtCobroItemStateChanged

        String pago = txtCobro.getSelectedItem().toString();
        if (pago=="Cobro a mi cuenta") {
        for (RegistrarTarje tarjeta : tarjeta) {
            cboTarjetas.removeAllItems();
            cboTarjetas.addItem(tarjeta.getNumero());
        }
        }else{
        cboTarjetas.removeAllItems();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCobroItemStateChanged

    private void txtFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaActionPerformed

        File archivo;
        String Factura = "Factura";
        try {
            archivo = new File ("C:\\Users\\Oreld\\Downloads\\"+Factura+".txt");
            if (archivo.createNewFile()) {
                JOptionPane.showMessageDialog(this,"La factura se a descargado y esta en la tuta correspondiente");
            }else{
                JOptionPane.showMessageDialog(this,"La factura ya se encuentra en su sistema");
            }
            FileWriter escribir = new FileWriter(archivo, true);
            escribir.write(contador);
            escribir.write("  ");
            escribir.write(codigoPaquete);
            escribir.write("  ");
            escribir.write(txtDepOrigen.getSelectedItem().toString());
            escribir.write("  ");
            escribir.write(txtDepDestino.getSelectedItem().toString());
            escribir.write("  ");
            escribir.write(txtCobro.getSelectedItem().toString());
            escribir.write("  ");
            escribir.write(txtNumeroPaquete.getSelectedItem().toString());
            escribir.write("  ");
            escribir.write(txtDatosFacturacion.getText());
            escribir.write("  ");
            escribir.write(String.valueOf(Precio));
            escribir.write("  ");
            escribir.close();
        } catch(Exception e){
        }
        
        




        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaActionPerformed

    private void cboTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTarjetasActionPerformed

    private void txtDatosFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosFacActionPerformed

        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatosFacActionPerformed

    private void cboTarjetas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTarjetas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTarjetas1ActionPerformed

    private void txtDatosFacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtDatosFacItemStateChanged

        if (txtDatosFac.getSelectedItem().toString()=="Datos de facturación") {
            String pago = txtCobro.getSelectedItem().toString();
         cboTarjetas1.removeAllItems();
        for (DatosFactu datos : datos) {
           
            cboTarjetas1.addItem(datos.getNit());
        }
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatosFacItemStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboTarjetas;
    private javax.swing.JComboBox<String> cboTarjetas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> txtCobro;
    private javax.swing.JButton txtCotizar;
    private javax.swing.JComboBox<String> txtDatosFac;
    private javax.swing.JTextField txtDatosFacturacion;
    private javax.swing.JComboBox<String> txtDepDestino;
    private javax.swing.JComboBox<String> txtDepOrigen;
    private javax.swing.JButton txtEnviarPago;
    private javax.swing.JToggleButton txtFactura;
    private javax.swing.JButton txtGuia;
    private javax.swing.JComboBox<String> txtMunDestino;
    private javax.swing.JComboBox<String> txtMunOrigen;
    private javax.swing.JComboBox<String> txtNumeroPaquete;
    private javax.swing.JComboBox<String> txtServicio;
    private javax.swing.JButton txtVolver;
    // End of variables declaration//GEN-END:variables
}
